### ISSUE TITLE
Reuse api on a different url?

### ISSUE THREAD

**Issue by shantp** [MartinKolb1987/DOMPTEUR#1]
I tried to use my edit-id on a different url with the same layout template but it only seems to load my selected elements if the url is the same. It would be useful to be able to reuse the "schema" I already set on a previous page if I am scraping many pages that have the same layout of data.

**Comment by MartinKolb1987** [comment]
it is possible to use the same scraping layout on a different uri:

https://dompteur.io/api/v1/YOUR-UNIQUE-ID/top-down/json?customRequestUri=' + encodeURIComponent('your-scraping-uri');

e.g.: 

https://dompteur.io/api/v1/123456/top-down/json?customRequestUri=' + encodeURIComponent('https://google.com');

**Comment by shantp** [comment]
Where do I put this code? I can't find an area in the extension to do this.

**Comment by MartinKolb1987** [comment]
dompteur generates your own unique uri. You have to add the parameter at the end 

?customRequestUri=theDomainWhichYouWantToScrapeWithTheSameScrapingLayout.com

of the generated api uri.

fyi: At the moment it‘s not possible to duplicate the edit-layout to another uri. It‘s only possible to use the scraping layout. If you want to change/edit it, you have to go to the first "primary" uri and change selected elements. You can use the  additonal parameter customRequestUri for example to extract data from a site with pagination. 

Let‘s make it more clear:
1. go to the URI you want to scrape (e.g. www.youruri.com)
2. dompteur generates your unique api uri
3. send a xhr to the api uri an you will receive the extracted elements data... right?
4. you want to use the same request scraping layout for for another uri – maybe page 2...
--> so add the ?customRequestUri=WholeUriPage2
5. now you get the data from page 2
